/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */
plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")
    testImplementation("com.google.code.gson:gson:2.8.5")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "apted.util.CommandLine"
    }
}

// Include test classes and private members into javadoc.
// javadoc {
//   classpath += sourceSets.test.compileClasspath
//   source += sourceSets.test.allJava
//   options.memberLevel = JavadocMemberLevel.PRIVATE
// }

// Enable printing to standard output while testing.
// test {
//   testLogging.showStandardStreams = true
// }
